[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32 @ 6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -I src
    -I src/meshtastic
    -D CORE_DEBUG_LEVEL=0
    -D PB_FIELD_32BIT=1
    -O2

board_build.partitions = no_ota.csv

lib_deps =
    fdivitto/FabGL @ ^1.0.9
    nanopb/Nanopb @ ^0.4.9
